### ISSUE TITLE
Resolved: DropdownMenu does not show onClick in reactstrap v8.0.0 if react-dom is not up-to-date with react

### ISSUE THREAD

**Issue by jonrandahl** [reactstrap/reactstrap#1516]
- components: `Dropdown, DropdownToggle, & DropdownMenu`
- reactstrap version `8.0.0`
- react version `16.8.6`
- _**react-dom version**_ `16.8.6`
- bootstrap version `4.5.1`

### What is happening?

I updated the entire **reactstrap** package to benefit from the work committed into this version, specifically for the **toasts** to alert users. The new toasts were working as expected when I was testing locally; however, when I went to action another component, namely the Dropdown, the expected DropdownMenu would not appear?

Upon checking the console for issues I found this error being reported multiple times:
```
uncaught TypeError: this.context.toggle is not a function
```

Upon further research, I stumbled on this [SO article](https://stackoverflow.com/a/55774495/5760177) which pointed to that fact that while my `React` version was up-to-date [`16.8.6`], upon closer examination of my package.json I found that the `react-dom` package was not at the same version which mirrored the same issue reported on SO.

### What should be happening?

When clicking on a Dropdown component the dropdown toggle should toggle the dropdown menu.

### Steps to reproduce issue

1. update **reactstrap** to `8.0.0`
2. verify **react-dom** version is lower than `16.8.6`
3. click on a dropdown component to view the menu
4. nothing happens

### Error message in console

```
uncaught TypeError: this.context.toggle is not a function
```

### Further comments
I'm not sure if this is directly related to `react-dom` or another library which depends on that; however, it might be beneficial for anyone who stumbles on this issue to check their versions and update if possible!

Thanks for all the hard work on this package, and all the components!

**Comment by zinartcode** [comment]
May 31 !!  Is anyone working on it? Have the same issue with react-16.4.0 and reactstrap 8.0.1

**Comment by jonrandahl** [comment]
@zinartcode I just ran into this again when updating to 8.0.1. Check your `react-dom` version to be sure it’s up to date with the recommendations! Hope this helps!

**Comment by dongyaoling** [comment]
Any update?

**Comment by zinartcode** [comment]
I was able to get it working by downgrading to 6.4.0. My react and react-dom both 16.4.0. Hope this helps

**Comment by burtonator** [comment]
happens to me with react 16.11.0 and reactstrap 8.1.1.... 

ONLY with webpack though.... our Electron app which uses typescript directly doesn't have this problem.

**Comment by gabyrusu** [comment]
I have the same problem. I'm using react 16.13.1, react-dom 16.13.1 and reactstrap 8.4.1

**Comment by jonrandahl** [comment]
Closing as resolved, apologies nonetheless for the "slight" delay! 😜
